# Generated by Django 5.2.8 on 2025-11-18 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_skill_remove_profile_skills_profile_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bio',
            new_name='address',
        ),
    ]
