# Generated by Django 5.2.8 on 2025-11-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_companyprofile_company_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
