# Generated by Django 5.2.8 on 2025-11-21 16:19

from django.db import migrations

def convert_skills_to_list(apps, schema_editor):
    UserProfile = apps.get_model('profiles', 'UserProfile')
    for profile in UserProfile.objects.all():
        if profile.skills and isinstance(profile.skills, str):
            # Convert comma-separated string to list
            skills = [skill.strip() for skill in profile.skills.split(',') if skill.strip()]
            profile.skills = skills
            profile.save()

def reverse_skills_to_text(apps, schema_editor):
    UserProfile = apps.get_model('profiles', 'UserProfile')
    for profile in UserProfile.objects.all():
        if profile.skills and isinstance(profile.skills, list):
            profile.skills = ', '.join(profile.skills)
            profile.save()

class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_userprofile_skills'),
    ]

    operations = [
        migrations.RunPython(convert_skills_to_list, reverse_skills_to_text),
    ]
