# Generated by Django 5.2.8 on 2025-12-16 04:24

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20251121_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='skills',
            field=models.JSONField(blank=True, default=profiles.models.default_skills),
        ),
    ]
