# Generated by Django 5.2.8 on 2025-12-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='education_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
