# Generated by Django 5.2.8 on 2025-12-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_userprofile_education_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='company_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
