# Generated by Django 5.2.8 on 2025-11-28 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follows', '0001_initial'),
    ]

    operations = [
    ]
