# Generated by Django 5.2.8 on 2025-12-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='experience',
            field=models.CharField(choices=[('0-1', '0-1 years'), ('1-3', '1-3 years'), ('3-5', '3-5 years'), ('5-10', '5-10 years'), ('10+', '10+ years')], db_index=True, default='0-1', max_length=10),
        ),
    ]
