# Generated by Django 5.2.8 on 2025-11-21 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
