# Generated by Django 5.2.8 on 2025-11-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_post', '0002_alter_jobpost_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='requirements',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
