# Generated by Django 5.2.8 on 2025-12-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_post', '0002_jobpost_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='experience',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
