# Generated by Django 5.2.8 on 2025-11-21 16:18

from django.db import migrations
import json

def convert_requirements_to_list(apps, schema_editor):
    JobPost = apps.get_model('job_post', 'JobPost')
    for job in JobPost.objects.all():
        if job.requirements and isinstance(job.requirements, str):
            # Convert comma-separated string to list
            skills = [skill.strip() for skill in job.requirements.split(',') if skill.strip()]
            job.requirements = skills
            job.save()

def reverse_requirements_to_text(apps, schema_editor):
    JobPost = apps.get_model('job_post', 'JobPost')
    for job in JobPost.objects.all():
        if job.requirements and isinstance(job.requirements, list):
            job.requirements = ', '.join(job.requirements)
            job.save()

class Migration(migrations.Migration):

    dependencies = [
        ('job_post', '0003_alter_jobpost_requirements'),
    ]

    operations = [
        migrations.RunPython(convert_requirements_to_list, reverse_requirements_to_text),
    ]
