# Generated by Django 5.2.8 on 2025-12-16 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_post', '0003_alter_jobpost_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
