# Generated by Django 5.2.8 on 2025-11-21 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_post', '0004_auto_20251121_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='company_name',
        ),
    ]
