# Generated by Django 5.2.8 on 2025-12-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_post', '0004_alter_jobpost_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
