# Generated by Django 5.2.8 on 2025-12-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_post', '0005_jobpost_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
