# Generated by Django 5.2.8 on 2025-11-25 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_post', '0006_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='work_mode',
            field=models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'On-site')], db_index=True, default='onsite', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_type',
            field=models.CharField(choices=[('fulltime', 'Full time'), ('parttime', 'Part time'), ('intern', 'Intern')], db_index=True, default='fulltime', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='location',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
