# Generated by Django 5.2.8 on 2025-12-16 08:06

from django.db import migrations

def set_jobs_active(apps, schema_editor):
    JobPost = apps.get_model('job_post', 'JobPost')
    JobPost.objects.all().update(is_active=True)

def reverse_set_jobs_active(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('job_post', '0006_alter_jobpost_is_active'),
    ]

    operations = [
        migrations.RunPython(set_jobs_active, reverse_set_jobs_active),
    ]
