# Generated by Django 5.2.8 on 2025-11-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_post', '0007_jobpost_work_mode_alter_jobpost_job_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('resume_review', 'Resume Review'), ('interview_scheduled', 'Interview Scheduled'), ('interviewed', 'Interviewed'), ('selected', 'Selected'), ('rejected', 'Rejected')], default='applied', max_length=20),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
