# Generated by Django 5.2.8 on 2025-12-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('follow', 'Follow'), ('post', 'Post'), ('like', 'Like'), ('comment', 'Comment'), ('job_post', 'Job Post'), ('job_application', 'Job Application')], max_length=20),
        ),
    ]
